language: java
jdk:
  - oraclejdk8
  - openjdk8

branches:
  only:
    - master

install:
  - echo "skip 'gradle assemble' step"

script:
  - ./gradlew build --continue
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/
  - rm -f  .gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  .gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/